### ISSUE TITLE
Memory lake issue.

### ISSUE THREAD

**Issue by DixPatel009** [dldnh/make-movie#1]
Your Code works perfectly in my app to generate a video from UIImages. But it use a lot of memory and sometimes too many.
My tests on an iPhone XS Max show that you can pass about 180-200 images maximum. After this, the application crash because of memory excess.

I will try to use less memory but maybe you already have an idea ?

**Comment by dldnh** [comment]
this wasn't meant to be an optimal solution. I just found it difficult to copy/paste the code from stackoverflow.

for the case you describe, it would probably be best not to provide all of the images at once, but to return them one at a time from a function that can iterate over the set you wish to include. so instead of ImageAnimator taking an array of UIImage, maybe a closure that returns a single UIImage.
